
--OBTENER PROMEDIO
CREATE OR REPLACE FUNCTION FN_OBTENER_PROMEDIO_20191031354(TIPO_PROPIEDAD PROPERTYS.PROPERTY_TYPE%TYPE)
RETURN PROPERTYS.PRICE%TYPE
IS
    DATOS_PROPIEDADES SYS_REFCURSOR;
        
    CANT_PROPIEDADES NUMBER(3) := 0;
        
    SUMA_PROPIEDADES PROPERTYS.PRICE%TYPE := 0;
        
    PRECIO PROPERTYS.PRICE%TYPE;  
    
    PROMEDIO PROPERTYS.PRICE%TYPE;
BEGIN

      OPEN DATOS_PROPIEDADES FOR
        SELECT PRICE FROM PROPERTYS WHERE property_type = TIPO_PROPIEDAD;
        
        LOOP
            
            FETCH DATOS_PROPIEDADES INTO PRECIO;
            EXIT WHEN DATOS_PROPIEDADES%NOTFOUND;
            
            SUMA_PROPIEDADES := SUMA_PROPIEDADES+PRECIO;
            CANT_PROPIEDADES := CANT_PROPIEDADES+1;
            
        END LOOP;
        
        IF CANT_PROPIEDADES > 0 THEN
            PROMEDIO := SUMA_PROPIEDADES/CANT_PROPIEDADES;
        ELSE   
            PROMEDIO := 0;
        END IF;
        
        RETURN PROMEDIO;

END;


--OBTENER PROPIEDADES
CREATE OR REPLACE FUNCTION FN_OBTENER_PRO_20191031354(TIPO_PROPIEDAD PROPERTYS.PROPERTY_TYPE%TYPE)
RETURN SYS_REFCURSOR
IS
    PROMEDIO PROPERTYS.PRICE%TYPE;
    
    DATOS_PROPIEDADES SYS_REFCURSOR;
BEGIN

    PROMEDIO := FN_OBTENER_PROMEDIO_20191031354(TIPO_PROPIEDAD);

    OPEN DATOS_PROPIEDADES FOR
    SELECT * FROM PROPERTYS WHERE property_type = TIPO_PROPIEDAD AND PRICE >= PROMEDIO;
    
    RETURN DATOS_PROPIEDADES;
        
END;


--BLQOUE ANONIMOS
DECLARE
    
    DATOS_PRO SYS_REFCURSOR;
    
    TYPE TBL_PRO IS RECORD(
       ID_PROPERTY                     NUMBER,
        NIF_PROPERTY                   VARCHAR2(20),
        ADDRESS_PROP                   VARCHAR2(50),
        GEOGRAPHICAL_COORDS            VARCHAR2(30),
        BUILDING_DATE                  DATE,
        PUBLICATION_DATE_SALE          DATE,        
        PROPERTY_TYPE                  VARCHAR2(20),
        ID_SUP                         NUMBER,
        PRICE                          NUMBER  
    );
    
    FILA TBL_PRO;
    
BEGIN
    
    DATOS_PRO := FN_OBTENER_PRO_20191031354('Apartment');
    
    FETCH DATOS_PRO INTO FILA;
    
    IF DATOS_PRO%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO HAY DATOS');
    ELSE
        LOOP
        
            DBMS_OUTPUT.PUT_LINE(' ');
            DBMS_OUTPUT.PUT_LINE('ID PRO: ' || FILA.ID_PROPERTY);
            DBMS_OUTPUT.PUT_LINE('NIF PRO: ' || FILA.NIF_PROPERTY);
            DBMS_OUTPUT.PUT_LINE('DIRECCION PRO: ' || FILA.ADDRESS_PROP);
            DBMS_OUTPUT.PUT_LINE('COORDENADAS PRO: ' || FILA.GEOGRAPHICAL_COORDS);
            DBMS_OUTPUT.PUT_LINE('FECHA CONSTRUCCION PRO: ' || FILA.BUILDING_DATE);
            DBMS_OUTPUT.PUT_LINE('PUBLICACION FECHA PRO: ' || FILA.PUBLICATION_DATE_SALE);
            DBMS_OUTPUT.PUT_LINE('TIPO PRO: ' || FILA.PROPERTY_TYPE);
            DBMS_OUTPUT.PUT_LINE('ID SUP PRO: ' || FILA.ID_SUP);
            DBMS_OUTPUT.PUT_LINE('PRECIO PRO: ' || FILA.PRICE);
            DBMS_OUTPUT.PUT_LINE(' ');
            
            FETCH DATOS_PRO INTO FILA;
            EXIT WHEN DATOS_PRO%NOTFOUND;
        
        END LOOP;
    END IF;
    

END;





DESC PROPERTYS;


SELECT * FROM PROPERTYS;
